<?php
const PLA_ID = 'PLA_ID';
const PLA_MARCA = 'PLA_MARCA';
const PLA_TALLA = 'PLA_TALLA';
const PLA_COLOR = 'PLA_COLOR';
const PLA_MODIFICACION = 'PLA_MODIFICACION';
const PLA_ELIMINADO = 'PLA_ELIMINADO';
